openapi: 3.0.3
info:
  title: PR Reviewer Assignment Service (Test Task, Fall 2025)
  version: 1.0.0
tags:
  - name: Teams
    description: Операции c командой
  - name: Users
    description: Операции c юзерами
  - name: PullRequests
    description: Операции c пулРевестами
  - name: Health
    description: Операция проверки работы сервиса
paths:
  /team/add:
    post:
      tags:
        - Teams
      summary: Создать команду с участниками (создаёт/обновляет пользователей)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
            example:
              team_name: payments
              members:
                - user_id: u1
                  username: Alice
                  is_active: true
                - user_id: u2
                  username: Bob
                  is_active: true
      responses:
        '201':
          description: Команда создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  team:
                    $ref: '#/components/schemas/Team'
              example:
                team:
                  team_name: backend
                  members:
                    - user_id: u1
                      username: Alice
                      is_active: true
                    - user_id: u2
                      username: Bob
                      is_active: true
        '400':
          description: Команда уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_error'
              example:
                error:
                  code: TEAM_EXISTS
                  message: team_name already exists
        '500':
          description: Ошибка в работе сервиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              example:
                error:
                  code: INTERNAL_ERROR
                  message: internal service error
  /team/get:
    get:
      tags:
        - Teams
      summary: Получить команду с участниками
      parameters:
        - $ref: '#/components/parameters/TeamNameQuery'
      responses:
        '200':
          description: Объект команды
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
              example:
                team_name: backend
                members:
                  - user_id: u1
                    username: Alice
                    is_active: true
                  - user_id: u2
                    username: Bob
                    is_active: true
        '404':
          description: Команда не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
              example:
                error:
                  code: NOT_FOUND
                  message: team_name not found
        '500':
          description: Ошибка в работе сервиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              example:
                error:
                  code: INTERNAL_ERROR
                  message: internal service error
  /users/setIsActive:
    post:
      tags:
        - Users
      summary: Установить флаг активности пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - is_active
              properties:
                user_id:
                  type: string
                  minLength: 1
                  maxLength: 50
                  description: Идентификатор пользователя
                is_active:
                  type: boolean
                  escription: Флаг активности пользователя
            example:
              user_id: u2
              is_active: false
      responses:
        '200':
          description: Обновлённый пользователь
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
              example:
                user:
                  user_id: u2
                  username: Bob
                  team_name: backend
                  is_active: false
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
              example:
                error:
                  code: NOT_FOUND
                  message: user not found
        '500':
          description: Ошибка в работе сервиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              example:
                error:
                  code: INTERNAL_ERROR
                  message: internal service error
  /pullRequest/create:
    post:
      tags:
        - PullRequests
      summary: Создать PR и автоматически назначить до 2 ревьюверов из команды автора
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pull_request_id
                - pull_request_name
                - author_id
              properties:
                pull_request_id:
                  type: string
                  minLength: 1
                  maxLength: 50
                  description: Уникальный ID PR
                pull_request_name:
                  type: string
                  minLength: 1
                  maxLength: 255
                  description: Название PR
                author_id:
                  type: string
                  minLength: 1
                  maxLength: 50
                  description: ID автора PR
            example:
              pull_request_id: pr-1001
              pull_request_name: Add search
              author_id: u1
      responses:
        '201':
          description: PR создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  pr:
                    $ref: '#/components/schemas/PullRequest'
              example:
                pr:
                  pull_request_id: pr-1001
                  pull_request_name: Add search
                  author_id: u1
                  status: OPEN
                  assigned_reviewers:
                    - u2
                    - u3
        '404':
          description: Автор/команда не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
              example:
                error:
                  code: NOT_FOUND
                  message: autgor/team not found
        '409':
          description: Нарушение доменных правил переназначения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conflict_error'
              example:
                error:
                  code: PR_EXISTS
                  message: PR id already exists
        '500':
          description: Ошибка в работе сервиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              example:
                error:
                  code: INTERNAL_ERROR
                  message: internal service error
  /pullRequest/merge:
    post:
      tags:
        - PullRequests
      summary: Пометить PR как MERGED (идемпотентная операция)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pull_request_id
              properties:
                pull_request_id:
                  type: string
                  minLength: 1
                  maxLength: 100
                  description: Уникальный ID PR
            example:
              pull_request_id: pr-1001
      responses:
        '200':
          description: PR в состоянии MERGED
          content:
            application/json:
              schema:
                type: object
                properties:
                  pr:
                    $ref: '#/components/schemas/PullRequest'
              example:
                pr:
                  pull_request_id: pr-1001
                  pull_request_name: Add search
                  author_id: u1
                  status: MERGED
                  assigned_reviewers:
                    - u2
                    - u3
                  mergedAt: '2025-10-24T12:34:56Z'
        '404':
          description: PR  не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
              example:
                error:
                  code: NOT_FOUND
                  message: pr not found
        '500':
          description: Ошибка в работе сервиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              example:
                error:
                  code: INTERNAL_ERROR
                  message: internal service error
  /pullRequest/reassign:
    post:
      tags:
        - PullRequests
      summary: Переназначить конкретного ревьювера на другого из его команды
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pull_request_id
                - old_user_id
              properties:
                pull_request_id:
                  type: string
                  minLength: 1
                  maxLength: 50
                old_user_id:
                  type: string
                  minLength: 1
                  maxLength: 50
            example:
              pull_request_id: pr-1001
              old_reviewer_id: u2
      responses:
        '200':
          description: Переназначение выполнено
          content:
            application/json:
              schema:
                type: object
                required:
                  - pr
                  - replaced_by
                properties:
                  pr:
                    $ref: '#/components/schemas/PullRequest'
                  replaced_by:
                    type: string
                    description: user_id нового ревьювера
              example:
                pr:
                  pull_request_id: pr-1001
                  pull_request_name: Add search
                  author_id: u1
                  status: OPEN
                  assigned_reviewers:
                    - u3
                    - u5
                replaced_by: u5
        '404':
          description: PR или пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
              example:
                error:
                  code: NOT_FOUND
                  message: user/pr not found
        '409':
          description: Нарушение доменных правил переназначения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conflict_error'
              examples:
                merged:
                  summary: Нельзя менять после MERGED
                  value:
                    error:
                      code: PR_MERGED
                      message: cannot reassign on merged PR
                notAssigned:
                  summary: Пользователь не был назначен ревьювером
                  value:
                    error:
                      code: NOT_ASSIGNED
                      message: reviewer is not assigned to this PR
                noCandidate:
                  summary: Нет доступных кандидатов
                  value:
                    error:
                      code: NO_CANDIDATE
                      message: no active replacement candidate in team
        '500':
          description: Ошибка в работе сервиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              example:
                error:
                  code: INTERNAL_ERROR
                  message: internal service error
  /users/getReview:
    get:
      tags:
        - Users
      summary: Получить PR'ы, где пользователь назначен ревьювером
      parameters:
        - $ref: '#/components/parameters/UserIdQuery'
      responses:
        '200':
          description: Список PR'ов пользователя
          content:
            application/json:
              schema:
                type: object
                required:
                  - user_id
                  - pull_requests
                properties:
                  user_id:
                    type: string
                    minLength: 1
                    maxLength: 50
                  pull_requests:
                    type: array
                    items:
                      $ref: '#/components/schemas/PullRequestShort'
              example:
                user_id: u2
                pull_requests:
                  - pull_request_id: pr-1001
                    pull_request_name: Add search
                    author_id: u1
                    status: OPEN
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
              example:
                error:
                  code: NOT_FOUND
                  message: user not found
        '500':
          description: Ошибка в работе сервиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
              example:
                error:
                  code: INTERNAL_ERROR
                  message: internal service error
components:
  schemas:
    TeamMember:
      type: object
      required:
        - user_id
        - username
        - is_active
      properties:
        user_id:
          type: string
          minLength: 1
          maxLength: 50
          description: Уникальный ID пользователя
        username:
          type: string
          minLength: 1
          maxLength: 255
          description: Имя пользователя
        is_active:
          type: boolean
          description: Активен ли пользователь
    Team:
      type: object
      required:
        - team_name
        - members
      properties:
        team_name:
          type: string
          minLength: 1
          maxLength: 255
          description: Уникальное имя команды
        members:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/TeamMember'
    bad_request_error:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - TEAM_EXISTS
                - PR_EXISTS
              description: |
                Внутренние коды ошибок:
                - TEAM_EXISTS: команда сущесвует
                - PR_EXISTS: Pull Request существует
            message:
              type: string
              description: Описание ошибки
    internal_server_error:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - INTERNAL_ERROR
              description: |
                Внутренние коды ошибок:
                - INTERNAL_ERROR - ошибка в работе сервиса
            message:
              type: string
              description: Описание ошибки
    not_found_error:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - NOT_FOUND
              description: |
                Внутренние коды ошибок:
                - NOT_FOUND - значения нет 
            message:
              type: string
              description: Описание ошибки
    User:
      type: object
      required:
        - user_id
        - username
        - team_name
        - is_active
      properties:
        user_id:
          type: string
          minLength: 1
          maxLength: 50
          description: Уникальный ID пользователя
        username:
          type: string
          minLength: 1
          maxLength: 100
          description: Имя пользователя
        team_name:
          type: string
          minLength: 1
          maxLength: 100
          description: Название команды пользователя
        is_active:
          type: boolean
          description: Активен ли пользователь
    PullRequest:
      type: object
      required:
        - pull_request_id
        - pull_request_name
        - author_id
        - status
        - assigned_reviewers
      properties:
        pull_request_id:
          type: string
        pull_request_name:
          type: string
        author_id:
          type: string
        status:
          type: string
          enum:
            - OPEN
            - MERGED
        assigned_reviewers:
          type: array
          items:
            type: string
          description: user_id назначенных ревьюверов (0..2)
        createdAt:
          type: string
          format: date-time
          nullable: true
        mergedAt:
          type: string
          format: date-time
          nullable: true
    conflict_error:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - PR_MERGED
                - NOT_ASSIGNED
                - NO_CANDIDATE
                - PR_EXISTS
              description: |
                Внутренние коды ошибок:
                - PR_MERGED: Нельзя менять после MERGED
                - NOT_ASSIGNED: Пользователь не был назначен ревьювером
                - NO_CANDIDATE: Нет доступных кандидатов
                - PR_EXISTS: Пулреквест уже есть 
            message:
              type: string
              description: Описание ошибки
    PullRequestShort:
      type: object
      required:
        - pull_request_id
        - pull_request_name
        - author_id
        - status
      properties:
        pull_request_id:
          type: string
        pull_request_name:
          type: string
        author_id:
          type: string
        status:
          type: string
          enum:
            - OPEN
            - MERGED
  parameters:
    TeamNameQuery:
      name: team_name
      in: query
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 255
      description: Уникальное имя команды
    UserIdQuery:
      name: user_id
      in: query
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 50
      description: Идентификатор пользователя
x-ogen:
  target: ./shared/pkg/openapi/reviewerservice/v1
  package: reviewerservice
  clean: true
